# Copyright (c) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Generate runtime ISA properties from the amdisa profiles."""

from pathlib import Path

_AMDGPU_ARCH_ORDER = (
    'cdna1',
    'cdna2',
    'cdna3',
    'cdna4',
    'rdna1',
    'rdna2',
    'rdna3',
    'rdna3_5',
    'rdna4',
    'cdna5',
)


def emit_isa_properties(output_dir: str, specs) -> Path:
    """Emit a constexpr runtime property map for the supplied AMDGPU ISAs."""
    profiles = {
        getattr(spec, 'arch_name', name): spec.profile for name, spec, _ in specs
    }
    unknown = profiles.keys() - set(_AMDGPU_ARCH_ORDER)
    if unknown:
        raise ValueError(f'unsupported ISA property entries: {sorted(unknown)}')

    cases = []
    max_addressable_vgprs_per_wf = 0
    for name in _AMDGPU_ARCH_ORDER:
        profile = profiles.get(name)
        if profile is None:
            continue
        enum_name = name.upper()
        supports_wgp_mode = 'true' if profile.supports_wgp_mode else 'false'
        mode_has_gpr_idx_en = 'true' if profile.supports_gpr_idx else 'false'
        descriptor_sgpr_count_encoded = (
            'true' if profile.descriptor_sgpr_count_encoded else 'false'
        )
        uses_ttmp_workgroup_ids = 'true' if profile.uses_ttmp_workgroup_ids else 'false'
        uses_cluster_ttmp_workgroup_ids = (
            'true' if profile.uses_cluster_ttmp_workgroup_ids else 'false'
        )
        wave_state_layout = f'WaveStateLayout::{profile.wave_state_layout.value}'
        compute_tmpring_wavesize_granule = profile.compute_tmpring_wavesize_granule
        compute_tmpring_wavesize_bits = profile.compute_tmpring_wavesize_bits
        wave_size = profile.wave_size
        wave_size_max = profile.wave_size_max
        vmcnt_capacity = profile.vmcnt_capacity
        lgkmcnt_capacity = profile.lgkmcnt_capacity
        addressable_vgprs = profile.max_addressable_vgprs_per_wf
        vgpr_count_granule_wave32 = profile.descriptor_vgpr_count_granule_wave32
        vgpr_count_granule_wave64 = profile.descriptor_vgpr_count_granule_wave64
        max_addressable_vgprs_per_wf = max(
            max_addressable_vgprs_per_wf, addressable_vgprs
        )
        cases += [
            f'  case ROCJITSU_CODE_ARCH_{enum_name}:',
            '    return {',
            f'        .supports_wgp_mode = {supports_wgp_mode},',
            f'        .mode_has_gpr_idx_en = {mode_has_gpr_idx_en},',
            f'        .descriptor_sgpr_count_encoded = {descriptor_sgpr_count_encoded},',
            f'        .uses_ttmp_workgroup_ids = {uses_ttmp_workgroup_ids},',
            f'        .uses_cluster_ttmp_workgroup_ids = {uses_cluster_ttmp_workgroup_ids},',
            f'        .wave_state_layout = {wave_state_layout},',
            f'        .compute_tmpring_wavesize_granule = {compute_tmpring_wavesize_granule},',
            f'        .compute_tmpring_wavesize_bits = {compute_tmpring_wavesize_bits},',
            f'        .wave_size = {wave_size},',
            f'        .wave_size_max = {wave_size_max},',
            f'        .vmcnt_capacity = {vmcnt_capacity},',
            f'        .lgkmcnt_capacity = {lgkmcnt_capacity},',
            f'        .max_addressable_vgprs_per_wf = {addressable_vgprs},',
            f'        .descriptor_vgpr_count_granule_wave32 = {vgpr_count_granule_wave32},',
            f'        .descriptor_vgpr_count_granule_wave64 = {vgpr_count_granule_wave64},',
            '    };',
        ]

    lines = [
        '// Copyright (c) 2026 Advanced Micro Devices, Inc.',
        '// SPDX-License-Identifier: MIT',
        '//',
        '// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.',
        '// See lib/python/amdisa/README.md for regeneration instructions.',
        '',
        '#ifndef ROCJITSU_ISA_ARCH_AMDGPU_GENERATED_SHARED_ISA_PROPERTIES_H_',
        '#define ROCJITSU_ISA_ARCH_AMDGPU_GENERATED_SHARED_ISA_PROPERTIES_H_',
        '',
        '#include "rocjitsu/base/api.h"',
        '',
        '#include <cstdint>',
        '#include <optional>',
        '',
        'namespace rocjitsu {',
        '',
        'enum class WaveStateLayout : uint8_t {',
        '  Legacy,',
        '  Gfx12,',
        '  Gfx12_5,',
        '};',
        '',
        'struct IsaProperties {',
        '  bool supports_wgp_mode = false;',
        '  bool mode_has_gpr_idx_en = false;',
        '  bool descriptor_sgpr_count_encoded = true;',
        '  bool uses_ttmp_workgroup_ids = false;',
        '  bool uses_cluster_ttmp_workgroup_ids = false;',
        '  WaveStateLayout wave_state_layout = WaveStateLayout::Legacy;',
        '  uint32_t compute_tmpring_wavesize_granule = 0;',
        '  uint32_t compute_tmpring_wavesize_bits = 0;',
        '  uint32_t wave_size = 0;',
        '  uint32_t wave_size_max = 0;',
        '  uint8_t vmcnt_capacity = 0;   ///< Zero when VMCNT is absent.',
        '  uint8_t lgkmcnt_capacity = 0; ///< Zero when LGKMCNT is absent.',
        '  uint32_t max_addressable_vgprs_per_wf = 0;',
        '  uint32_t descriptor_vgpr_count_granule_wave32 = 0;',
        '  uint32_t descriptor_vgpr_count_granule_wave64 = 0;',
        '};',
        '',
        'inline constexpr uint32_t MAX_SUPPORTED_ADDRESSABLE_VGPRS_PER_WF = '
        f'{max_addressable_vgprs_per_wf};',
        '',
        '[[nodiscard]] constexpr IsaProperties isa_properties(rj_code_arch_t arch) {',
        '  switch (arch) {',
        *cases,
        '  default:',
        '    return {};',
        '  }',
        '}',
        '',
        '[[nodiscard]] constexpr std::optional<uint32_t>',
        'descriptor_vgpr_count_granule_for_wavefront(rj_code_arch_t arch, uint32_t wavefront_size) {',
        '  const auto properties = isa_properties(arch);',
        '  if (wavefront_size == 32 && properties.descriptor_vgpr_count_granule_wave32 != 0)',
        '    return properties.descriptor_vgpr_count_granule_wave32;',
        '  if (wavefront_size == 64 && properties.descriptor_vgpr_count_granule_wave64 != 0)',
        '    return properties.descriptor_vgpr_count_granule_wave64;',
        '  return std::nullopt;',
        '}',
        '',
        '} // namespace rocjitsu',
        '',
        '#endif // ROCJITSU_ISA_ARCH_AMDGPU_GENERATED_SHARED_ISA_PROPERTIES_H_',
        '',
    ]

    output = Path(output_dir) / 'shared' / 'isa_properties.h'
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('\n'.join(lines))
    return output
