/*************************************************************************
 * Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

// Fail-loud stub floor for src/rccl_wrap.cc's host-only microtest, compiled
// into rccl-UnitTestsMicro alongside p2p.cc/rma_proxy_progress.cc's own
// tests. #include-ing the whole 1771-line rccl_wrap.cc (via WRAP_CC_PATH)
// pulls in the DDA / CE / symmetric-kernel / hierarchical backend-selection
// machinery even though the covered functions (see wrap-test.cc) don't reach
// all of it yet. Everything below satisfies the link closure; entries the
// current tests never reach default to abort()-on-call so an accidentally
// exercised path fails fast instead of silently returning a wrong answer.
//
// Deliberately NOT reusing nccl_stubs.cc / bootstrap_stubs.cc / topo_stubs.cc
// / transport_stubs.cc here: those are curated for init.cc and each already
// stubs commSetUnrollFactor and rcclCommSetP2pShiftSize as abort() floors for
// init.cc's benefit -- both are REAL functions defined by rccl_wrap.cc
// itself, so linking those files together with this one would be a
// duplicate-symbol error. fakes/nccl_fakes.cc (p2p.cc's fakes, already part
// of this binary) has no such conflict -- p2p.cc never calls either function
// -- so this file's logging globals (below) are shared with nccl_fakes.cc's
// rather than duplicated.
//
// RCCL_PARAM / NCCL_PARAM: every RCCL_PARAM(...) invocation textually inside
// rccl_wrap.cc is redirected by wrap-test.cc to route through a g_loadParam
// std::function hook (same mechanism as init-test.cc's redirect), so a test
// can flip one param's value between cases -- see wrap-test.cc's redirector
// comment. The few ncclParamXxx / rcclParamXxx symbols rccl_wrap.cc declares
// `extern` and calls without a local RCCL_PARAM/NCCL_PARAM invocation (their
// generator lives in another .cc) are stubbed below instead.

#include <dlfcn.h>

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <optional>
#include <string>
#include <unordered_map>

#include "wrap_fakes.h"

#include "nccl.h"
#include "comm.h"
#include "debug.h"
#include "rccl_common.h"
#include "enqueue.h"     // NCCL_ALGO_*/NCCL_PROTO_*, ncclSimInfo_t (getAlgoInfo's param)
#include "group.h"
#include "ce_coll.h"
#include "sym_kernels.h"
#include "dev_runtime.h"
#include "strongstream.h"
#include "algorithms/dda/all_reduce/dda_all_reduce.h"
#include "algorithms/dda/all_gather/dda_all_gather.h"
#include "algorithms/dda/reduce_scatter/dda_reduce_scatter.h"
#include "amdsmi_wrap.h"

// ---------------------------------------------------------------------------
// Logging infrastructure. WARN/INFO (debug.h) expand to ncclDebugLog(); three
// of the current Tier-1 units (rcclGetAlgoProtoIndex, rcclGetAlgoName,
// rcclGetProtocolName) call WARN on their invalid-input arms, and tests assert
// on that text via gtest's stderr capture.
//
// ncclDebugLevel / ncclDebugMask / ncclDebugNoWarn / ncclDebugLog() itself
// are defined once, by fakes/nccl_fakes.cc, which this binary already links
// for p2p.cc's tests -- defining them again here would be a duplicate-symbol
// error. ncclDebugMask's default there (0) differs from what this file used
// when it was its own standalone binary (~0ULL), but that's not observable
// by anything currently covered: WARN(...) calls ncclDebugLog() unconditionally
// regardless of mask, and no function covered so far calls INFO(...) (which
// does check ncclDebugLevel/ncclDebugMask) at all. A future test that needs to
// capture an INFO(...) line should raise both explicitly first, e.g. with
// RcclUnitTesting::ScopedDebugLogging, rather than relying on either side's
// default.
// ---------------------------------------------------------------------------
FILE* ncclDebugFile = nullptr;
char  ncclLastError[1024] = {};

// ---------------------------------------------------------------------------
// ncclParamXxx / rcclParamXxx symbols NOT generated by an RCCL_PARAM/NCCL_PARAM
// invocation inside rccl_wrap.cc itself (see file header comment). Trivial
// real behaviour (return the production default) rather than abort(): these
// are read on essentially every call into the file's channel/DDA tuning
// paths, so an abort-floor here would make even unrelated tests crash before
// reaching the function they actually meant to exercise.
//
// Unlike NCCL_NUM_ALGORITHMS/ncclNumFuncs above, there's no importable
// constant for "the current default" here -- NCCL_PARAM/RCCL_PARAM bakes
// deftVal directly as an inline macro-argument literal (see param.h), not a
// separately declared symbol, so a static_assert can't check it. Instead,
// wrap-test.cc's ParamDefaults_MatchProductionSource test reads the real
// graph/connect.cc / enqueue.cc source at run time and confirms the exact
// NCCL_PARAM/RCCL_PARAM(...) invocation text below still matches -- a
// run-time tripwire where a compile-time one isn't possible.
// ---------------------------------------------------------------------------
int64_t ncclParamMinNchannels() { return -2; }              // graph/connect.cc:832
int64_t ncclParamMaxNchannels() { return -2; }              // graph/connect.cc:833
int64_t rcclParamForceCe() { return 1; }                    // enqueue.cc:3796

// ncclParamLaunchOrderImplicit: upgraded to a settable hook (unlike the three
// plain scalars above) so a test can drive rcclDdaEnabled's
// `ncclParamLaunchOrderImplicit() != 0` disjunct independently -- the real
// default (0, "explicit launch order") favors the common case, matching the
// other three.
static int64_t DefaultParamLaunchOrderImplicit() { return 0; }  // enqueue.cc:1985
std::function<int64_t()> g_paramLaunchOrderImplicit = DefaultParamLaunchOrderImplicit;
int64_t ncclParamLaunchOrderImplicit() { return g_paramLaunchOrderImplicit(); }

// The settable env-var fake (SetMicroEnv/SetMicroEnvAbsent/ClearMicroEnv,
// the bare-getenv() link-level interposer, and ncclGetEnv) is NOT defined
// here: fakes/env_fakes.cc is the shared owner of src/misc/param.cc + getenv
// interposition for every microtest binary (see MICROTEST_README.md's
// "Where a fake belongs"). rccl_wrap.cc's several bare getenv() call sites
// (rcclSetPxn, rcclSetP2pNetChunkSize, rcclUpdateCollectiveProtocol,
// rcclUpdateThreadThreshold, ...) are covered by that same interposer.
// ncclGroupDepth is NOT faked here: group-test.cc (also part of this binary
// since the rccl-UnitTestsMicro merge) compiles the real group.cc, which
// defines it -- a second copy here would be a duplicate-symbol error. Its
// real default (0, "not grouped") is what every rccl_wrap.cc test so far
// assumes, same as when this was a hand-copied stub.

// rcclUseAinic: real definition (transport/net.cc:343) does hardware NIC
// detection via std::call_once; not linked here (pulls in the IB/net
// transport layer). false -- "not an AINIC" -- is the common-case default,
// now a controllable seam so rcclUseAllGatherDirect's AINIC-disabled branch
// (never exercised before) can be proven too.
static bool DefaultUseAinic() { return false; }
std::function<bool()> g_useAinic = DefaultUseAinic;
bool rcclUseAinic() { return g_useAinic(); }

// ncclPxnDisable: real definition graph/paths.cc:740, reads comm fields set
// up during channel/topology construction this lean binary doesn't build.
// Not to be confused with rcclSetPxn (already tested), which computes
// comm->pxnDisable itself and never calls this getter. 0 -- "PXN not
// disabled" -- is the common-case default, now a controllable seam so
// rcclUseReduceScatterDirect's PXN-disabled branch (never exercised before)
// can be proven too.
static int DefaultPxnDisable(struct ncclComm* /*comm*/) { return 0; }
std::function<int(struct ncclComm*)> g_pxnDisable = DefaultPxnDisable;
int ncclPxnDisable(struct ncclComm* comm) { return g_pxnDisable(comm); }

// ncclDevFuncUnrollGenerated: extern bool const[NCCL_NUM_UNROLLS]. Real array,
// not abort-floor -- commSetUnrollFactor indexes it unconditionally on every
// call, including the manual-override path any Tier-1-adjacent test might
// exercise. All-true is the safe default: "every unroll factor was built".
//
// Confirmed NOT safely upgradeable to a test seam: device.h's `extern bool
// const [...]` declaration is transitively visible in this TU too (this
// file doesn't include device.h directly, but something in its include
// chain does) -- dropping `const` here is a hard redefinition-with-
// different-type compile error, not just a lurking runtime risk. Leaving
// this const and documented, not forced through.
//
// Drift watchdog: without one, a new unroll factor added to RCCL would not be
// caught here -- the extra array slot would silently zero-initialize to false,
// quietly changing behavior. The check is a RUNTIME test
// (FakeTableDrift_UnrollCountMatchesProduction in wrap-test.cc), not a
// static_assert, for the same reason as the enum-count checks below.
const bool ncclDevFuncUnrollGenerated[NCCL_NUM_UNROLLS] = {true, true, true, true, true, true};

// ncclCommCount: real behaviour by default (de-risks future tests),
// but a controllable seam so rcclGetAlgoInfo's NCCLCHECK(ncclCommCount(...))
// failure arm (never exercised -- every prior test let this succeed) can be
// proven too.
static ncclResult_t DefaultCommCount(const ncclComm_t comm, int* count) {
  if (count) *count = comm ? comm->nRanks : 0;
  return ncclSuccess;
}
std::function<ncclResult_t(const ncclComm_t, int*)> g_commCount = DefaultCommCount;
ncclResult_t ncclCommCount(const ncclComm_t comm, int* count) { return g_commCount(comm, count); }

// ---------------------------------------------------------------------------
// ncclAlgoToString / ncclProtoToString / ncclFuncToString / ncclDatatypeToString:
// faithful copies of collectives.cc's trivial switch tables, NOT abort-floors
// -- rcclGetAlgoName/rcclGetProtocolName (Tier-1, tested below) delegate to
// the first two for native algo/protocol values, and rcclOverrideProtocol/
// rcclOverrideAlgorithm (out of scope here) use all four in WARN messages. Real
// collectives.cc is not linked here: it pulls in the DDA/symmetric-kernel/
// nvtx dependency chain this lean binary otherwise avoids entirely (see the
// file header comment). Each function below names the exact definition it
// copies, so a drift is checkable without leaving this file.
//
// NCCL_ALGO_* / NCCL_PROTO_* are plain #defines, not a real enum, so the
// compiler can't warn on a switch missing a newly-added case the way it could
// for an enum. ncclFunc_t / ncclDataType_t ARE real enums with trailing count
// sentinels (ncclNumFuncs, ncclNumTypes), so those are checkable too.
//
// All four counts are pinned by a RUNTIME test
// (FakeTableDrift_StringTableCountsMatchProduction in wrap-test.cc),
// deliberately NOT by static_assert. This file is linked into
// rccl-UnitTestsMicro, which p2p/rma/group/devcomm tests all share: a
// compile-time assert here would break every one of those builds over a
// constant none of them read. A failing test names the drift just as loudly
// and only fails the suite that cares. CI runs these tests, so the drift is
// caught either way.
// ---------------------------------------------------------------------------
const char* ncclFuncToString(ncclFunc_t fn) {  // collectives.cc:32
  switch (fn) {
  case ncclFuncAllGather: return "AllGather";
  case ncclFuncAllReduce: return "AllReduce";
  case ncclFuncAlltoAll: return "AlltoAll";
  case ncclFuncAlltoAllv: return "AlltoAllv";
  case ncclFuncBroadcast: return "Broadcast";
  case ncclFuncGather: return "Gather";
  case ncclFuncRecv: return "Recv";
  case ncclFuncReduce: return "Reduce";
  case ncclFuncReduceScatter: return "ReduceScatter";
  case ncclFuncScatter: return "Scatter";
  case ncclFuncSendRecv: return "SendRecv";
  case ncclFuncSend: return "Send";
  case ncclFuncPutSignal: return "PutSignal";
  case ncclFuncSignal: return "Signal";
  case ncclFuncWaitSignal: return "WaitSignal";
  default: return "Invalid";
  }
}

const char* ncclDatatypeToString(ncclDataType_t type) {  // collectives.cc:86
  switch (type) {
  case ncclInt8: return "ncclInt8";
  case ncclInt32: return "ncclInt32";
  case ncclUint32: return "ncclUint32";
  case ncclInt64: return "ncclInt64";
  case ncclUint64: return "ncclUint64";
  case ncclFloat16: return "ncclFloat16";
  case ncclFloat32: return "ncclFloat32";
  case ncclFloat64: return "ncclFloat64";
  case ncclBfloat16: return "ncclBfloat16";
  case ncclFloat8e4m3: return "ncclFloat8e4m3";
  case ncclFloat8e5m2: return "ncclFloat8e5m2";
  default: return "Unknown";
  }
}

const char* ncclAlgoToString(int algo) {  // collectives.cc:115
  switch (algo) {
  case NCCL_ALGO_TREE: return "TREE";
  case NCCL_ALGO_RING: return "RING";
  case NCCL_ALGO_COLLNET_DIRECT: return "COLLNET_DIRECT";
  case NCCL_ALGO_COLLNET_CHAIN: return "COLLNET_CHAIN";
  case NCCL_ALGO_NVLS: return "NVLS";
  case NCCL_ALGO_NVLS_TREE: return "NVLS_TREE";
  case NCCL_ALGO_PAT: return "PAT";
  default: return "Unknown";
  }
}

const char* ncclProtoToString(int proto) {  // collectives.cc:136
  switch (proto) {
  case NCCL_PROTO_LL: return "LL";
  case NCCL_PROTO_LL128: return "LL128";
  case NCCL_PROTO_SIMPLE: return "SIMPLE";
  default: return "Unknown";
  }
}

// ---------------------------------------------------------------------------
// Controllable seams for the "High-tier" group (rcclSelectAllReduce/
// AllGather/ReduceScatter, rcclHierarchicalAlgoInfo, rcclGetAlgoInfo,
// rcclGetCollImplInfo, rcclSymkQuery/rcclSymKGetInfo's deep path). Previously
// all abort()-floors (see MICROTEST_README.md, "Adding more controllable
// seams" for the pattern followed here); upgraded so wrap-test.cc can drive
// each branch of those dispatchers directly. Every default below reproduces
// the safe, common "this fast path doesn't apply" case so existing tests
// upstream of these seams are unaffected -- verified by rereading each real
// call site before choosing it.
// ---------------------------------------------------------------------------

// Drives `symEligible` in all three rcclSelectXxx functions. Default false:
// "no symmetric-window kernel requested," letting the DDA/CE/Direct/plain
// paths run, matching every existing (guard-only) test's expectations.
static bool DefaultIsSymmetricKernelRequested(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, const void*,
                                              void*) {
  return false;
}
std::function<bool(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, const void*, void*)>
    g_isSymmetricKernelRequested = DefaultIsSymmetricKernelRequested;
bool isSymmetricKernelRequested(struct ncclComm* comm, ncclFunc_t coll, int symkOp, ncclDataType_t datatype,
                                size_t nElts, const void* sendbuff, void* recvbuff) {
  return g_isSymmetricKernelRequested(comm, coll, symkOp, datatype, nElts, sendbuff, recvbuff);
}

// Drives `ceCapturing` on rcclSelectAllReduce's live (query=false) path only
// (query=true uses the caller-supplied graphCapturingHint instead). Default:
// "not currently capturing a graph" (ncclCudaGraphNone's real, inline
// semantics -- graphId == ULLONG_MAX), the common non-graph-mode case.
static ncclResult_t DefaultCudaGetCapturingGraph(struct ncclCudaGraph* graph, hipStream_t, int graphUsageMode) {
  *graph = ncclCudaGraphNone(graphUsageMode);
  return ncclSuccess;
}
std::function<ncclResult_t(struct ncclCudaGraph*, hipStream_t, int)> g_cudaGetCapturingGraph =
    DefaultCudaGetCapturingGraph;
ncclResult_t ncclCudaGetCapturingGraph(struct ncclCudaGraph* graph, hipStream_t stream, int graphUsageMode) {
  return g_cudaGetCapturingGraph(graph, stream, graphUsageMode);
}

// Window/registration-state trio, driving hasSysmemSegment/winRegType in
// AllReduce's and AllGather's CE checks. Defaults: no window found (a plain,
// unregistered buffer -- the common case for operands not set up as
// symmetric windows), no sysmem segment, and the "neither side registered"
// reg-type.
static ncclResult_t DefaultDevrFindWindow(struct ncclComm*, void const*, struct ncclDevrWindow** window) {
  *window = nullptr;
  return ncclSuccess;
}
std::function<ncclResult_t(struct ncclComm*, void const*, struct ncclDevrWindow**)> g_devrFindWindow =
    DefaultDevrFindWindow;
ncclResult_t ncclDevrFindWindow(struct ncclComm* comm, void const* ptr, struct ncclDevrWindow** window) {
  return g_devrFindWindow(comm, ptr, window);
}

static bool DefaultDevrWindowHasSysmemSegment(struct ncclDevrWindow*) { return false; }
std::function<bool(struct ncclDevrWindow*)> g_devrWindowHasSysmemSegment = DefaultDevrWindowHasSysmemSegment;
bool ncclDevrWindowHasSysmemSegment(struct ncclDevrWindow* window) { return g_devrWindowHasSysmemSegment(window); }

static ncclResult_t DefaultGetSymRegType(struct ncclDevrWindow*, struct ncclDevrWindow*, ncclSymRegType_t* type) {
  *type = ncclSymSendNonregRecvNonreg;
  return ncclSuccess;
}
std::function<ncclResult_t(struct ncclDevrWindow*, struct ncclDevrWindow*, ncclSymRegType_t*)> g_getSymRegType =
    DefaultGetSymRegType;
ncclResult_t ncclGetSymRegType(struct ncclDevrWindow* sendWin, struct ncclDevrWindow* recvWin,
                               ncclSymRegType_t* type) {
  return g_getSymRegType(sendWin, recvWin, type);
}

// Symmetric-kernel deep path (past rcclSymkQuery's four already-tested early
// guards). Defaults: init succeeds (common case), but "not available" so
// rcclSymkQuery still returns false by default -- a test opts a specific
// case into the real kernel-pick path via ScopedHook.
static ncclResult_t DefaultSymkInitOnce(struct ncclComm*) { return ncclSuccess; }
std::function<ncclResult_t(struct ncclComm*)> g_symkInitOnce = DefaultSymkInitOnce;
ncclResult_t ncclSymkInitOnce(struct ncclComm* comm) { return g_symkInitOnce(comm); }

static bool DefaultSymkAvailable(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t) { return false; }
std::function<bool(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t)> g_symkAvailable = DefaultSymkAvailable;
bool ncclSymkAvailable(struct ncclComm* comm, ncclFunc_t coll, int op, ncclDataType_t dt, size_t count) {
  return g_symkAvailable(comm, coll, op, dt, count);
}

// Default: succeeds but reports "no kernel found" (ncclSymkKernelId_Count),
// matching the sentinel rcclSymkQuery itself checks for and rejects -- a
// graceful "queried, nothing matched" default rather than a real pick.
static ncclResult_t DefaultSymkPickKernel(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, size_t, int,
                                          ncclSymRegType_t, float* estTimeUs, ncclSymkKernelId* kernelId,
                                          int* maxChannels, int* nWarps, bool* forced) {
  *estTimeUs = 0.0f;
  *kernelId = ncclSymkKernelId_Count;
  *maxChannels = 0;
  *nWarps = 0;
  *forced = false;
  return ncclSuccess;
}
std::function<ncclResult_t(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, size_t, int, ncclSymRegType_t,
                            float*, ncclSymkKernelId*, int*, int*, bool*)>
    g_symkPickKernel = DefaultSymkPickKernel;
ncclResult_t ncclSymkPickKernel(struct ncclComm* comm, ncclFunc_t coll, int op, ncclDataType_t dt, size_t count,
                                size_t count2, int n, ncclSymRegType_t regType, float* estTimeUs,
                                ncclSymkKernelId* kernelId, int* maxChannels, int* nWarps, bool* forced) {
  return g_symkPickKernel(comm, coll, op, dt, count, count2, n, regType, estTimeUs, kernelId, maxChannels, nWarps,
                          forced);
}

static bool DefaultSymkKernelIdIsLL(int) { return false; }
std::function<bool(int)> g_symkKernelIdIsLL = DefaultSymkKernelIdIsLL;
bool rcclSymkKernelIdIsLL(int kernelId) { return g_symkKernelIdIsLL(kernelId); }

// CE availability trio. Defaults false/false/1: CE fast paths off by
// default (a test opts in via ScopedHook), a small positive block count so
// a test that DOES opt CE in without also overriding this gets a sane,
// nonzero channel count rather than a silently-wrong 0.
static bool DefaultCeAvailable(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, ncclSymRegType_t) { return false; }
std::function<bool(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, ncclSymRegType_t)> g_ceAvailable =
    DefaultCeAvailable;
bool ncclCeAvailable(struct ncclComm* comm, ncclFunc_t coll, int op, ncclDataType_t dt, ncclSymRegType_t regType) {
  return g_ceAvailable(comm, coll, op, dt, regType);
}

static bool DefaultCeScratchAvailable(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, ncclSymRegType_t) {
  return false;
}
std::function<bool(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, ncclSymRegType_t)> g_ceScratchAvailable =
    DefaultCeScratchAvailable;
bool ncclCeScratchAvailable(struct ncclComm* comm, ncclFunc_t coll, int op, ncclDataType_t dt,
                            ncclSymRegType_t regType) {
  return g_ceScratchAvailable(comm, coll, op, dt, regType);
}

static int DefaultCeLocalReduceBlocks(ncclDataType_t, size_t) { return 1; }
std::function<int(ncclDataType_t, size_t)> g_ceLocalReduceBlocks = DefaultCeLocalReduceBlocks;
int ncclCeLocalReduceBlocks(ncclDataType_t dt, size_t count) { return g_ceLocalReduceBlocks(dt, count); }

// rcclAllReduceShouldTakeDdaPath: real body lives in collectives.cc (not
// linked here), same abort-floor-turned-seam treatment as the rest. Default
// false: DDA not taken, letting CE-registered/symmetric/plain-kernel run.
static bool DefaultAllReduceShouldTakeDdaPath(const struct ncclComm*, size_t, ncclDataType_t, bool, bool) {
  return false;
}
std::function<bool(const struct ncclComm*, size_t, ncclDataType_t, bool, bool)> g_allReduceShouldTakeDdaPath =
    DefaultAllReduceShouldTakeDdaPath;
bool rcclAllReduceShouldTakeDdaPath(const struct ncclComm* comm, size_t count, ncclDataType_t dt, bool symEligible,
                                    bool ceAllReduceAllowed) {
  return g_allReduceShouldTakeDdaPath(comm, count, dt, symEligible, ceAllReduceAllowed);
}

// getAlgoInfo / rcclKernelPackedChannels: rccl_wrap.cc `extern`-declares both
// itself (their real definitions live in enqueue.cc / device-side tuning,
// outside this TU's link closure), so no separate declaration is needed here.
// Default getAlgoInfo fills in a sane, generic Ring/Simple/1-channel answer
// (the universal plain-kernel fallback every rcclSelectXxx eventually falls
// to); default rcclKernelPackedChannels passes the tuning-cap channel count
// through unpacked, a safe no-op default.
static ncclResult_t DefaultGetAlgoInfo(struct ncclComm*, struct ncclTaskColl* task, int, int, int, ncclSimInfo_t*) {
  task->algorithm = NCCL_ALGO_RING;
  task->protocol = NCCL_PROTO_SIMPLE;
  task->nMaxChannels = 1;
  return ncclSuccess;
}
std::function<ncclResult_t(struct ncclComm*, struct ncclTaskColl*, int, int, int, ncclSimInfo_t*)> g_getAlgoInfo =
    DefaultGetAlgoInfo;
ncclResult_t getAlgoInfo(struct ncclComm* comm, struct ncclTaskColl* task, int collNetSupport, int nvlsSupport,
                         int numPipeOps, ncclSimInfo_t* simInfo) {
  return g_getAlgoInfo(comm, task, collNetSupport, nvlsSupport, numPipeOps, simInfo);
}

static int DefaultKernelPackedChannels(struct ncclComm*, ncclFunc_t, size_t, ncclDataType_t, int, int nMaxChannels) {
  return nMaxChannels;
}
std::function<int(struct ncclComm*, ncclFunc_t, size_t, ncclDataType_t, int, int)> g_kernelPackedChannels =
    DefaultKernelPackedChannels;
int rcclKernelPackedChannels(struct ncclComm* comm, ncclFunc_t func, size_t count, ncclDataType_t dt, int protocol,
                             int nMaxChannels) {
  return g_kernelPackedChannels(comm, func, count, dt, protocol, nMaxChannels);
}

// rcclLL128ElemsPerThreadFromArch is `inline` in archinfo.h (transitively
// included), so no stub is needed here.

// getFirmwareVersion()'s sole dependency. Settable hook, same std::function
// shape as fakes/nccl_fakes.cc's, so a test can script a canned firmware
// response or a failure without touching the real AMD-SMI layer.
static ncclResult_t DefaultAmdSmiGetFirmwareVersion(uint32_t /*devIdx*/, uint64_t* fwVersion) {
  *fwVersion = 0;
  return ncclSuccess;
}
std::function<ncclResult_t(uint32_t, uint64_t*)> g_amdSmiGetFirmwareVersion = DefaultAmdSmiGetFirmwareVersion;
ncclResult_t amd_smi_getFirmwareVersion(uint32_t devIdx, uint64_t* fwVersion) {
  return g_amdSmiGetFirmwareVersion(devIdx, fwVersion);
}

// --- Per-collective DDA eligibility/blocks (24 functions total) ---
// Every *Eligible defaults false (DDA path not eligible by default, letting
// CE-registered/symmetric/hierarchical/Direct/plain-kernel run, matching
// every existing test's expectations); every *Blocks defaults to 1 (a sane
// nonzero placeholder for a test that opts a path in without separately
// overriding the channel count). One seam pair per function, same
// Default*/g_hookName pattern as every other seam in this file.

// --- AllReduce DDA (dda_all_reduce.h) ---
static bool DefaultAllReduceDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_allReduceDdaIpcEligible = DefaultAllReduceDdaIpcEligible;
bool ncclAllReduceDdaIpcEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                 ncclRedOp_t op) {
  return g_allReduceDdaIpcEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultAllReduceDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_allReduceDdaFabricEligible = DefaultAllReduceDdaFabricEligible;
bool ncclAllReduceDdaFabricEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                    ncclRedOp_t op) {
  return g_allReduceDdaFabricEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultAllReduceDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_allReduceDdaFabricLLEligible = DefaultAllReduceDdaFabricLLEligible;
bool ncclAllReduceDdaFabricLLEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                      ncclRedOp_t op) {
  return g_allReduceDdaFabricLLEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultAllReduceDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t,
                                                   ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_allReduceDdaFabricLL128Eligible = DefaultAllReduceDdaFabricLL128Eligible;
bool ncclAllReduceDdaFabricLL128Eligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                         ncclRedOp_t op) {
  return g_allReduceDdaFabricLL128Eligible(comm, sb, rb, count, dt, op);
}

static uint32_t DefaultAllReduceDdaIpcBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allReduceDdaIpcBlocks = DefaultAllReduceDdaIpcBlocks;
uint32_t ncclAllReduceDdaIpcBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allReduceDdaIpcBlocks(comm, count, dt);
}

static uint32_t DefaultAllReduceDdaFabricBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allReduceDdaFabricBlocks =
    DefaultAllReduceDdaFabricBlocks;
uint32_t ncclAllReduceDdaFabricBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allReduceDdaFabricBlocks(comm, count, dt);
}

static uint32_t DefaultAllReduceDdaFabricLLBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allReduceDdaFabricLLBlocks =
    DefaultAllReduceDdaFabricLLBlocks;
uint32_t ncclAllReduceDdaFabricLLBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allReduceDdaFabricLLBlocks(comm, count, dt);
}

static uint32_t DefaultAllReduceDdaFabricLL128Blocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allReduceDdaFabricLL128Blocks =
    DefaultAllReduceDdaFabricLL128Blocks;
uint32_t ncclAllReduceDdaFabricLL128Blocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allReduceDdaFabricLL128Blocks(comm, count, dt);
}

// --- AllGather DDA (dda_all_gather.h) ---
static bool DefaultAllGatherDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) { return false; }
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t)> g_allGatherDdaIpcEligible =
    DefaultAllGatherDdaIpcEligible;
bool ncclAllGatherDdaIpcEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaIpcEligible(comm, sb, rb, count, dt);
}

static bool DefaultAllGatherDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) { return false; }
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t)> g_allGatherDdaFabricEligible =
    DefaultAllGatherDdaFabricEligible;
bool ncclAllGatherDdaFabricEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricEligible(comm, sb, rb, count, dt);
}

static bool DefaultAllGatherDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t)> g_allGatherDdaFabricLLEligible =
    DefaultAllGatherDdaFabricLLEligible;
bool ncclAllGatherDdaFabricLLEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricLLEligible(comm, sb, rb, count, dt);
}

static bool DefaultAllGatherDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t)> g_allGatherDdaFabricLL128Eligible =
    DefaultAllGatherDdaFabricLL128Eligible;
bool ncclAllGatherDdaFabricLL128Eligible(ncclComm* comm, const void* sb, void* rb, size_t count,
                                         ncclDataType_t dt) {
  return g_allGatherDdaFabricLL128Eligible(comm, sb, rb, count, dt);
}

static uint32_t DefaultAllGatherDdaIpcBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allGatherDdaIpcBlocks = DefaultAllGatherDdaIpcBlocks;
uint32_t ncclAllGatherDdaIpcBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaIpcBlocks(comm, count, dt);
}

static uint32_t DefaultAllGatherDdaFabricBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allGatherDdaFabricBlocks =
    DefaultAllGatherDdaFabricBlocks;
uint32_t ncclAllGatherDdaFabricBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricBlocks(comm, count, dt);
}

static uint32_t DefaultAllGatherDdaFabricLLBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allGatherDdaFabricLLBlocks =
    DefaultAllGatherDdaFabricLLBlocks;
uint32_t ncclAllGatherDdaFabricLLBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricLLBlocks(comm, count, dt);
}

static uint32_t DefaultAllGatherDdaFabricLL128Blocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allGatherDdaFabricLL128Blocks =
    DefaultAllGatherDdaFabricLL128Blocks;
uint32_t ncclAllGatherDdaFabricLL128Blocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricLL128Blocks(comm, count, dt);
}

// --- ReduceScatter DDA (dda_reduce_scatter.h) ---
static bool DefaultReduceScatterDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_reduceScatterDdaIpcEligible = DefaultReduceScatterDdaIpcEligible;
bool ncclReduceScatterDdaIpcEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                     ncclRedOp_t op) {
  return g_reduceScatterDdaIpcEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultReduceScatterDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t,
                                                  ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_reduceScatterDdaFabricEligible = DefaultReduceScatterDdaFabricEligible;
bool ncclReduceScatterDdaFabricEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                        ncclRedOp_t op) {
  return g_reduceScatterDdaFabricEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultReduceScatterDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t,
                                                    ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_reduceScatterDdaFabricLLEligible = DefaultReduceScatterDdaFabricLLEligible;
bool ncclReduceScatterDdaFabricLLEligible(ncclComm* comm, const void* sb, void* rb, size_t count,
                                          ncclDataType_t dt, ncclRedOp_t op) {
  return g_reduceScatterDdaFabricLLEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultReduceScatterDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t,
                                                       ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_reduceScatterDdaFabricLL128Eligible = DefaultReduceScatterDdaFabricLL128Eligible;
bool ncclReduceScatterDdaFabricLL128Eligible(ncclComm* comm, const void* sb, void* rb, size_t count,
                                             ncclDataType_t dt, ncclRedOp_t op) {
  return g_reduceScatterDdaFabricLL128Eligible(comm, sb, rb, count, dt, op);
}

static uint32_t DefaultReduceScatterDdaIpcBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_reduceScatterDdaIpcBlocks =
    DefaultReduceScatterDdaIpcBlocks;
uint32_t ncclReduceScatterDdaIpcBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_reduceScatterDdaIpcBlocks(comm, count, dt);
}

static uint32_t DefaultReduceScatterDdaFabricBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_reduceScatterDdaFabricBlocks =
    DefaultReduceScatterDdaFabricBlocks;
uint32_t ncclReduceScatterDdaFabricBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_reduceScatterDdaFabricBlocks(comm, count, dt);
}

static uint32_t DefaultReduceScatterDdaFabricLLBlocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_reduceScatterDdaFabricLLBlocks =
    DefaultReduceScatterDdaFabricLLBlocks;
uint32_t ncclReduceScatterDdaFabricLLBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_reduceScatterDdaFabricLLBlocks(comm, count, dt);
}

static uint32_t DefaultReduceScatterDdaFabricLL128Blocks(ncclComm*, size_t, ncclDataType_t) { return 1; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_reduceScatterDdaFabricLL128Blocks =
    DefaultReduceScatterDdaFabricLL128Blocks;
uint32_t ncclReduceScatterDdaFabricLL128Blocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_reduceScatterDdaFabricLL128Blocks(comm, count, dt);
}
