// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

/// @file instruction.h
/// @brief Abstract instruction representation with operands, flags, and dynamic state.

#ifndef ROCJITSU_ISA_INSTRUCTION_H_
#define ROCJITSU_ISA_INSTRUCTION_H_

#include "rocjitsu/isa/arch/amdgpu/shared/memory_issue.h"
#include "rocjitsu/isa/operand.h"
#include "rocjitsu/result.h"
#include "util/intrusive_list.h"

#include <array>
#include <cassert>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

namespace rocjitsu {

/// @brief Instruction property flags.
enum InstFlags : uint64_t {
  /// @brief Unconditional branch.
  BRANCH = 1,
  /// @brief Conditional branch.
  COND_BRANCH = (1ULL << 1),
  /// @brief Indirect branch (target from register).
  INDIRECT_BRANCH = (1ULL << 2),
  /// @brief Indirect call (target from register, returns to fallthrough).
  INDIRECT_CALL = (1ULL << 3),
  /// @brief Terminates the program.
  PROGRAM_TERMINATOR = (1ULL << 4),
  /// @brief Executes immediately without scheduling latency.
  IMMEDIATELY_EXECUTED = (1ULL << 5),
  /// @brief Memory operation (load or store).
  MEMORY_OP = (1ULL << 6),
  /// @brief Wait-counter instruction (s_waitcnt, s_wait_loadcnt, s_wait_storecnt, etc.).
  WAITCNT = (1ULL << 7),
  /// @brief Barrier instruction (s_barrier, s_barrier_signal, s_barrier_wait).
  BARRIER = (1ULL << 8),
  /// @brief Matrix FMA instruction (v_mfma_*, v_smfmac_*).
  MFMA = (1ULL << 9),
  /// @brief AccVGPR move instruction (v_accvgpr_write, v_accvgpr_read, v_accvgpr_mov).
  ACCVGPR = (1ULL << 10),
  /// @brief Destination update is conditional and must not kill the old value.
  PREDICATED_DEF = (1ULL << 11),
  /// @brief Executes regardless of the EXEC mask (e.g. branches).
  IGNORES_EXEC = (1ULL << 12),
  /// @brief Writes the EXEC mask regardless of DST operands.
  WRITES_EXEC = (1ULL << 13),
  /// @brief The destination value is a scalar plain copy of a single source operand
  /// (e.g. s_mov). Lets EXEC-state analysis prove an all-ones EXEC write from an
  /// all-ones source.
  RESULT_COPY = (1ULL << 14),
  /// @brief The destination value is the scalar bitwise pure OR of the source operands
  /// (e.g. s_or, s_or_saveexec). Pure OR with an all-ones operand is all-ones
  /// regardless of the others.
  RESULT_OR = (1ULL << 15)
};

class BasicBlock;

/// @brief Base class for opaque per-instruction dynamic state.
///
/// @details ISA backends attach subclasses to carry mutable pipeline state (e.g.,
/// computed addresses, response buffers) that lives outside the autogenerated
/// encoding classes. The base class is ISA-neutral.
class DynamicInstState {
public:
  virtual ~DynamicInstState() = default;

  /// @brief Backend-defined tag for pipeline routing or dispatch.
  /// @returns Tag value.
  uint8_t tag() const { return tag_; }
  void set_tag(uint8_t t) { tag_ = t; }

protected:
  uint8_t tag_ = 0;
};

/// @brief Abstract base class that defines the API for an instruction.
class Instruction : public util::IListNode<Instruction, util::IListParent<BasicBlock>> {
public:
  /// @brief Function pointer type for direct (non-virtual) execute dispatch.
  /// @param self The instruction instance.
  /// @param ctx  ISA-specific execution context (cast to concrete type by impl).
  using ExecuteFn = void (*)(Instruction &self, void *ctx);

  /// @brief Construct an instruction with the given mnemonic.
  /// @param[in] mnemonic Human-readable mnemonic (must point to static storage
  ///            or storage that outlives the instruction — typically a string
  ///            literal or a member of the encoding base class).
  Instruction(std::string_view mnemonic, ExecuteFn exec, uint64_t src_loc = 0)
      : execute(exec), src_loc_(src_loc), mnemonic_(mnemonic) {}
  virtual ~Instruction() = default;

  /// @brief Pool allocator hooks, set by the decoder's enable_pool().
  /// Thread-local because each CU partition thread has its own decoder/pool.
  /// Instructions are wholly owned by their CU and always allocated/freed
  /// on the same thread.
  using AllocFn = void *(*)(void *pool, size_t size);
  using DeallocFn = void (*)(void *pool, void *ptr);
  static thread_local inline AllocFn alloc_fn_;
  static thread_local inline DeallocFn dealloc_fn_;
  static thread_local inline void *alloc_pool_;

  /// @brief Temporarily force instruction allocations onto the heap.
  ///
  /// @details C ABI entry points use this guard when instructions can outlive
  /// the decoder that produced them. It preserves the ambient allocator hooks
  /// and restores them on scope exit. Decoder destruction invalidates matching
  /// saved hooks so a scope never restores a pointer to a dead pool.
  class ScopedHeapAllocation {
  public:
    ScopedHeapAllocation()
        : saved_alloc_fn_(alloc_fn_), saved_dealloc_fn_(dealloc_fn_),
          saved_alloc_pool_(alloc_pool_), previous_scope_(active_scope_) {
      active_scope_ = this;
      alloc_fn_ = nullptr;
      dealloc_fn_ = nullptr;
      alloc_pool_ = nullptr;
    }

    ~ScopedHeapAllocation() {
      assert(active_scope_ == this && "allocation guards must be destroyed in stack order");
      alloc_fn_ = saved_alloc_fn_;
      dealloc_fn_ = saved_dealloc_fn_;
      alloc_pool_ = saved_alloc_pool_;
      active_scope_ = previous_scope_;
    }

    ScopedHeapAllocation(const ScopedHeapAllocation &) = delete;
    ScopedHeapAllocation &operator=(const ScopedHeapAllocation &) = delete;
    ScopedHeapAllocation(ScopedHeapAllocation &&) = delete;
    ScopedHeapAllocation &operator=(ScopedHeapAllocation &&) = delete;

  private:
    friend class Instruction;

    static thread_local inline ScopedHeapAllocation *active_scope_;
    AllocFn saved_alloc_fn_;
    DeallocFn saved_dealloc_fn_;
    void *saved_alloc_pool_;
    ScopedHeapAllocation *previous_scope_;
  };

  /// @brief Remove every active or saved reference to an allocator pool.
  /// @param[in] pool Pool that is being disabled or destroyed.
  static void invalidate_allocator_pool(void *pool) {
    if (alloc_pool_ == pool) {
      alloc_fn_ = nullptr;
      dealloc_fn_ = nullptr;
      alloc_pool_ = nullptr;
    }
    for (auto *scope = ScopedHeapAllocation::active_scope_; scope; scope = scope->previous_scope_) {
      if (scope->saved_alloc_pool_ != pool)
        continue;
      scope->saved_alloc_fn_ = nullptr;
      scope->saved_dealloc_fn_ = nullptr;
      scope->saved_alloc_pool_ = nullptr;
    }
  }

  static void *operator new(size_t size) {
    if (alloc_fn_)
      return alloc_fn_(alloc_pool_, size);
    return ::operator new(size);
  }

  static void operator delete(void *ptr) noexcept {
    if (dealloc_fn_) {
      dealloc_fn_(alloc_pool_, ptr);
      return;
    }
    ::operator delete(ptr);
  }

  Instruction(const Instruction &) = delete;
  Instruction &operator=(const Instruction &) = delete;
  Instruction(Instruction &&) = delete;
  Instruction &operator=(Instruction &&) = delete;

  /// @brief Direct execute dispatch.  Callers invoke as:
  ///   ``inst->execute(*inst, &ctx)``
  /// Each derived instruction class sets this to a trampoline that calls
  /// its ``execute_impl()`` method. In a model-only DBT image this is nullptr
  /// and must not be called. No virtual dispatch.
  const ExecuteFn execute;

  /// @brief Access the attached dynamic state, or nullptr if none.
  /// @returns Pointer to the dynamic state, or nullptr.
  DynamicInstState *data() { return data_.get(); }
  /// @copydoc data()
  const DynamicInstState *data() const { return data_.get(); }

  /// @brief Typed convenience accessor (unchecked static_cast).
  /// @tparam T Concrete DynamicInstState subclass.
  /// @returns Pointer to the dynamic state cast to @p T.
  template <typename T> T *data_as() {
    assert(dynamic_cast<T *>(data_.get()) != nullptr);
    return static_cast<T *>(data_.get());
  }
  /// @copydoc data_as()
  template <typename T> const T *data_as() const {
    assert(dynamic_cast<const T *>(data_.get()) != nullptr);
    return static_cast<const T *>(data_.get());
  }

  /// @brief Attach dynamic state to this instruction (transfers ownership).
  /// @param[in] d Dynamic state (ownership transferred).
  void set_data(std::unique_ptr<DynamicInstState> d) { data_ = std::move(d); }

  /// @brief The instruction's canonical semantic mnemonic.
  /// @returns Reference to the mnemonic used by analysis and execution consumers.
  std::string_view mnemonic() const { return mnemonic_; }

  /// @brief The instruction's total number of operands.
  /// @returns Sum of source and destination operand counts.
  int num_operands() const { return num_src_operands() + num_dst_operands(); }

  /// @brief The instruction's number of source operands.
  /// @returns Source operand count.
  int num_src_operands() const { return num_src_; }

  /// @brief The instruction's number of destination operands.
  /// @returns Destination operand count.
  int num_dst_operands() const { return num_dst_; }

  /// @brief Access a source operand by index.
  /// @param i  Operand index (0-based, must be < num_src_operands()).
  /// @returns Pointer to the operand, or nullptr if index out of range.
  [[nodiscard]] const Operand *src_operand(int i) const {
    return (i >= 0 && i < num_src_) ? src_operands_[i] : nullptr;
  }

  /// @brief Access a destination operand by index.
  /// @param i  Operand index (0-based, must be < num_dst_operands()).
  /// @returns Pointer to the operand, or nullptr if index out of range.
  [[nodiscard]] const Operand *dst_operand(int i) const {
    return (i >= 0 && i < num_dst_) ? dst_operands_[i] : nullptr;
  }

  /// @brief Size of the instruction's encoding in bytes.
  /// @returns Encoding size in bytes.
  int size() const { return size_; }

  /// @brief Previous decoded instruction in the same basic block.
  /// @returns The preceding instruction, or nullptr at the block boundary.
  [[nodiscard]] const Instruction *previous_instruction() const {
    if (parent_ == nullptr || prev_ == nullptr || prev_->parent_ != parent_)
      return nullptr;
    return static_cast<const Instruction *>(prev_);
  }

  /// @brief Next decoded instruction in the same basic block.
  /// @returns The following instruction, or nullptr at the block boundary.
  [[nodiscard]] const Instruction *next_instruction() const {
    if (parent_ == nullptr || next_ == nullptr || next_->parent_ != parent_)
      return nullptr;
    return static_cast<const Instruction *>(next_);
  }

  /// @brief Source byte offset of this instruction in the decoded text section.
  ///
  /// @details Most decoder users only care about the instruction encoding and
  /// leave this as zero. CFG builders decode from a text stream and pass the
  /// stream offset through Decoder::decode() so analyses can carry instruction
  /// pointers without a parallel offset wrapper.
  [[nodiscard]] uint64_t src_loc() const { return src_loc_; }

  /// @brief Whether this instruction is a direct branch.
  /// @retval true The instruction has BRANCH or COND_BRANCH metadata.
  /// @retval false The instruction is not a direct branch.
  bool is_branch() const { return flags_ & (BRANCH | COND_BRANCH); }

  /// @brief Whether this instruction is a memory operation.
  /// @retval true The instruction has the MEMORY_OP flag set.
  /// @retval false The instruction is not a memory operation.
  bool is_memory_op() const { return flags_ & MEMORY_OP; }

  /// @brief Return decoded AMDGPU memory-issue metadata, when present.
  /// @details AMDGPU generated memory-instruction constructors populate this
  /// descriptor. Other architectures and non-memory instructions return nullptr.
  [[nodiscard]] const amdgpu::MemoryIssueInfo *amdgpu_memory_issue_info() const {
    return memory_issue_info_.completion_class == amdgpu::MemoryCompletionClass::UNCLASSIFIED
               ? nullptr
               : &memory_issue_info_;
  }

  uint64_t flags() const { return flags_; }

  bool is_waitcnt() const { return flags_ & WAITCNT; }

  bool is_barrier() const { return flags_ & BARRIER; }

  bool is_mfma() const { return flags_ & MFMA; }

  bool is_accvgpr() const { return flags_ & ACCVGPR; }

  /// @brief Signed byte offset for a direct branch target.
  ///
  /// @details Generated ISA subclasses override this for direct branches whose
  /// label operand is a signed instruction-count delta. Indirect branches and
  /// non-branches return nullopt.
  [[nodiscard]] virtual std::optional<int64_t> branch_offset_bytes() const { return std::nullopt; }

  /// @brief Add registers implicitly read by this instruction.
  ///
  /// @details Used for encoded fields that affect execution but are not part of
  /// the printed operand list, such as FLAT/GLOBAL `saddr` addressing fields.
  virtual void implicit_uses(RegisterSet & /*uses*/) const {}

  /// @brief Report operands that are implicitly read, preserving their identity.
  ///
  /// @details Complements implicit_uses(): where that flattens hidden reads into
  /// a RegisterSet (losing operand role and width), this appends the source
  /// Operand pointers so a caller can resolve each with its own VGPR-MSB role and
  /// width — needed on gfx1250, where a partial-write/RMW op preserve-reads its
  /// destination and a swap preserve-reads both operands, each in its own bank.
  /// Only register-bearing implicit reads that originate from a decoded operand
  /// are reported here; encoded-field reads with no Operand (e.g. FLAT `saddr`)
  /// remain exclusive to implicit_uses(). The pointed-to Operands share this
  /// instruction's lifetime.
  virtual void implicit_use_operands(std::vector<const Operand *> & /*operands*/) const {}

  /// @brief Add registers implicitly written by this instruction.
  virtual void implicit_defs(RegisterSet & /*defs*/) const {}

  /// @brief Raw encoding words of this instruction.
  /// @returns Pointer to the encoding words (size()/4 words), or nullptr if not set.
  const uint32_t *raw_encoding() const { return raw_encoding_; }

  /// @brief Encoding format ID (the encoding prefix from the machine instruction).
  [[nodiscard]] uint16_t encoding_id() const { return encoding_id_; }

  /// @brief Opcode within the encoding format.
  [[nodiscard]] uint16_t opcode() const { return opcode_; }

  /// @brief Target feature bits required to decode this instruction form.
  ///
  /// The generated constructor records both mnemonic-wide and encoding-form
  /// requirements. Decoder instances compare this mask with the immutable
  /// feature set of their concrete GPU target before exposing the instruction.
  [[nodiscard]] uint64_t required_isa_features() const { return required_isa_features_; }

  /// @brief Produce the disassembly string for this instruction.
  ///
  /// @details On first call, generates and caches the disassembly string. Subsequent
  /// calls return the cached string.
  /// @returns Reference to the disassembly string.
  const std::string &disassemble() const {
    if (disassembly_.empty()) {
      append_mnemonic(disassembly_);
      bool first = true;
      // TODO: Include explicit fieldless operands (and/or implicit ones too).
      for (uint8_t operand_index = 0; operand_index < num_dst_; ++operand_index) {
        if (dst_operands_[operand_index]->is_fieldless())
          continue;
        disassembly_ += (first ? " " : ", ");
        append_dst_operand(disassembly_, operand_index);
        first = false;
      }
      for (uint8_t operand_index = 0; operand_index < num_src_; ++operand_index) {
        if (src_operands_[operand_index]->size_bits() == 0 ||
            src_operands_[operand_index]->is_fieldless())
          continue;
        if (omit_repeated_destination_sources_) {
          bool repeats_dst = false;
          for (uint8_t dst_index = 0; dst_index < num_dst_; ++dst_index)
            repeats_dst |= src_operands_[operand_index] == dst_operands_[dst_index];
          if (repeats_dst)
            continue;
        }
        disassembly_ += (first ? " " : ", ");
        append_src_operand(disassembly_, operand_index);
        first = false;
      }
      build_modifiers(disassembly_);
    }
    return disassembly_;
  }

protected:
  friend class Decoder;

  void set_memory_issue_info(
      amdgpu::WaitCounterType wait_counter_type, amdgpu::MemoryCompletionClass completion_class,
      std::optional<amdgpu::WaitCounterType> alternate_wait_counter_type = std::nullopt,
      bool exec_masked = true) {
    assert(completion_class != amdgpu::MemoryCompletionClass::UNCLASSIFIED);
    memory_issue_info_ = {wait_counter_type, completion_class, alternate_wait_counter_type,
                          exec_masked};
    flags_ |= MEMORY_OP;
  }

  void set_memory_issue_info(amdgpu::WaitCounterType wait_counter_type,
                             amdgpu::MemoryCompletionClass completion_class, bool exec_masked) {
    set_memory_issue_info(wait_counter_type, completion_class, std::nullopt, exec_masked);
  }

  /// @brief Size of the instruction's encoding in bytes.
  int size_ = 0;
  /// @brief Instruction's source operands (max 6). KEEP IN SYNC with
  /// CodeGenerator._SRC_OPERANDS_CAPACITY (the generator's overflow tripwire
  /// mirrors this size); resize both together.
  std::array<Operand *, 6> src_operands_{};
  uint8_t num_src_ = 0;
  /// @brief Instruction's destination operands (max 3). KEEP IN SYNC with
  /// CodeGenerator._DST_OPERANDS_CAPACITY; resize both together.
  std::array<Operand *, 3> dst_operands_{};
  uint8_t num_dst_ = 0;
  /// @brief Whether read/write operands are rendered only in destination position.
  bool omit_repeated_destination_sources_ = false;
  static_assert(sizeof(amdgpu::MemoryIssueInfo) <= 6,
                "memory issue metadata must fit Instruction's existing padding");
  /// @brief AMDGPU issue metadata; kept here to use padding before disassembly_.
  amdgpu::MemoryIssueInfo memory_issue_info_;
  /// @brief Append the encoding-specific mnemonic spelling used by disassembly.
  /// The default matches mnemonic(); encoding decorations may override it.
  virtual void append_mnemonic(std::string &out) const { out += mnemonic_; }
  /// @brief Append encoding attributes to the disassembly string (e.g. cache flags or DPP state).
  /// Overridden by encoding bases that have instruction attributes to display.
  /// Default: no modifiers. Called lazily by disassemble().
  virtual void build_modifiers(std::string & /*out*/) const {}
  /// @brief Append one destination operand to textual disassembly.
  virtual void append_dst_operand(std::string &out, uint8_t operand_index) const {
    out += dst_operands_[operand_index]->name();
  }
  /// @brief Append one source operand to textual disassembly.
  virtual void append_src_operand(std::string &out, uint8_t operand_index) const {
    out += src_operands_[operand_index]->name();
  }
  /// @brief Cached disassembly string.
  mutable std::string disassembly_;
  /// @brief Instruction property flags bitmask.
  uint64_t flags_ = 0;
  std::unique_ptr<DynamicInstState> data_;
  /// @brief Pointer to the raw encoding words (set by encoding base class constructors).
  const uint32_t *raw_encoding_ = nullptr;
  /// @brief Encoding format ID (the encoding prefix from the machine instruction).
  uint16_t encoding_id_ = 0;
  /// @brief Opcode within the encoding format.
  uint16_t opcode_ = 0;
  /// @brief Feature mask emitted from the ISA-variant manifest.
  // A 32-bit mask fits in the alignment padding before src_loc_. Keep this
  // compact: Instruction is on decode/simulation hot paths and every generated
  // instruction derives from it.
  uint32_t required_isa_features_ = 0;
  /// @brief Source byte offset assigned at construction or by Decoder::decode().
  uint64_t src_loc_ = 0;

protected:
  std::string_view mnemonic_;
};

/// @brief Return a callback from the per-ISA backend active during decoding.
Instruction::ExecuteFn current_instruction_execute(size_t instruction_id) noexcept;

/// @brief Abstract class that holds static ISA state for a specific instruction instance.
///
/// @details Provides a typed execute() taking the ISA-specific context. Subclasses override
/// this.
/// @tparam Isa ISA traits type providing a Context type alias.
template <typename Isa> class IsaInstruction : public Instruction {
public:
  using IsaType = Isa;

  /// @brief Construct an ISA instruction with the given mnemonic.
  /// @param[in] mnemonic Human-readable mnemonic string.
  IsaInstruction(std::string_view mnemonic, ExecuteFn exec_fn, uint64_t src_loc = 0)
      : Instruction(mnemonic, exec_fn, src_loc) {}

  /// @brief Accept encodings for formats without additional validation.
  template <typename... Args>
  static constexpr Result validate_encoding([[maybe_unused]] Args &&...args) noexcept {
    return Result::success();
  }

  /// @brief Helper to create an execute dispatch trampoline for a concrete type.
  ///
  /// The returned function pointer casts the base ``Instruction&`` to the
  /// concrete ``Derived&`` and calls ``execute_impl()`` on it.
  ///
  /// Usage in a constructor init-list:
  /// @code
  ///   AddInst(...) : RType("add", raw, make_exec_fn<AddInst>()) {}
  /// @endcode
  template <typename Derived> static constexpr ExecuteFn make_exec_fn() {
    return [](Instruction &self, void *ctx) {
      static_cast<Derived &>(self).execute_impl(*static_cast<typename Isa::Context *>(ctx));
    };
  }

  /// @brief Select a callback from the active immutable per-ISA table.
  static ExecuteFn selected_exec_fn(size_t instruction_id) {
    return current_instruction_execute(instruction_id);
  }

  /// @brief Select a callback using a generated, named execution ID.
  template <typename ExecutionId>
    requires std::is_enum_v<ExecutionId>
  static ExecuteFn selected_exec_fn(ExecutionId instruction_id) {
    return current_instruction_execute(static_cast<size_t>(instruction_id));
  }
};

} // namespace rocjitsu

#endif // ROCJITSU_ISA_INSTRUCTION_H_
